spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tRm9q3F3VpBpMp4QcM8
      secret-key: z5Dk9m7wo8c3YN32iqUoh4ukziyz0Q
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-zsc

  application:
    name: gulimall-third-party

server:
  port: 30000
